### ISSUE TITLE
Comment API

### ISSUE THREAD

**Issue by waternova** [shresh02/explainable_ML_public_policy#3]
API for comments:
POST /comments
```
{
  "factorId": 34,
  "user": "anon",
  "text": "This is a new comment."
}
```
Response:
```
{
  "id": 345
  "factorId": 34,
  "user": "anon",
  "text": "This is a new comment."
}
```

**Comment by ssj1977** [comment]
I added the following REST APIs (with django REST framework)

- (GET/POST) /api/model                        : Retrieve or Add a model
- (GET/POST) /api/factor                         : Retrieve or Add a factor
- (GET/POST) /api/comment                   : Retrieve or Add a comment
- (GET/POST) /api/user                            : Retrieve or Add a commet
- (GET) /api/getfactors/?model_id=        : Retrieve all factors of a model
- (GET) /api/getcomments/?factor_id=   : Retrieve all comments of a factor

**Comment by waternova** [comment]
TODO: make the current comments save to the server
